- nodeset:
    name: ara-centos-7
    nodes:
      - name: server
        label: centos-7

- nodeset:
    name: ara-ubuntu-bionic
    nodes:
      - name: server
        label: ubuntu-bionic

- job:
    name: ara-role-integration-base
    parent: base-minimal
    pre-run: zuul.d/playbooks/pre.yml
    timeout: 900
    roles:
      - name: ara
        zuul: openstack/ansible-role-ara
      - zuul: openstack-infra/zuul-jobs
      - zuul: openstack-infra/openstack-zuul-jobs
    required-projects:
      - openstack/ara

- job:
    name: ara-role-integration-centos-mod_wsgi
    parent: ara-role-integration-base
    run: zuul.d/playbooks/scenarios/mod_wsgi.yml
    nodeset: ara-centos-7

- job:
    name: ara-role-integration-ubuntu-mod_wsgi
    parent: ara-role-integration-base
    run: zuul.d/playbooks/scenarios/mod_wsgi.yml
    nodeset: ara-ubuntu-bionic

# - job:
#     name: ara-integration-ubuntu-xenial
#     parent: ara-integration-base
#     nodeset: ara-ubuntu-xenial
#     vars:
#       target: ubuntu
#       config:
#         ansible_version: 2.5.0
#         server: nginx
#         application: embedded
#         database: sqlite

- project:
    check:
      jobs:
        - ara-role-integration-centos-mod_wsgi
        - ara-role-integration-ubuntu-mod_wsgi
    gate:
      jobs:
        - ara-role-integration-centos-mod_wsgi
        - ara-role-integration-ubuntu-mod_wsgi
