---
#  Copyright (c) 2018 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA.  If not, see <http://www.gnu.org/licenses/>.

# This runs the ARA role with parameters to set up apache with mod_wsgi.
- name: Install ARA from source with mod_wsgi
  hosts: server
  vars:
    ara_override:
      config:
        host: 0.0.0.0
        application_root: /ara
      params:
        install:
          pip:
            method: source
            source: "{{ ansible_user_dir }}/src/git.openstack.org/openstack/ara"
      deployment:
        server: apache
        type: mod_wsgi
  tasks:
    - name: Include the ARA role
      include_role:
        name: ara

    - name: Ensure handlers are flushed
      meta: flush_handlers

    - name: Assert that the deployment worked
      include_tasks: validation.yml
